apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentiment-pvc
  namespace: sentiment-analysis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard  # Adjust based on your cluster's available storage classes